apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    rule_files:
      # - "first.rules"
      # - "second.rules"
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: cadvisor
        scheme: https
        scrape_interval: 5s
        static_configs:
          - targets: ['prometheus-agent:8080']
        kubernetes_sd_configs:
        - api_server: 'https://kubernetes.default.svc.cluster.local'
          role: endpoints
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            #insecure_skip_verify: true
kind: ConfigMap
