apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus-deployment
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-deployment
    spec:
      containers:
      - image: gcr.io/gke-workout/prometheus-image:latest
        imagePullPolicy: Always
        name: prometheus-image
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
        - mountPath: /prometheus/
          name: prometheus-storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-server-conf
        name: prometheus-config-volume
      - emptyDir: {}
        name: prometheus-storage-volume
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2018-09-19T17:00:23Z
    lastUpdateTime: 2018-09-19T17:00:23Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
