apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus-deployment
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-deployment
    spec:
      containers:
      - image: gcr.io/gke-workout/prometheus-image
        imagePullPolicy: Always
        name: prometheus-image
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: prometheus-config-volume
        - mountPath: /prometheus/
          name: prometheus-storage-volume
      - image: google/cadvisor:latest
        imagePullPolicy: Always
        name: cadvisor
        ports:
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-server-conf
        name: prometheus-config-volume
      - emptyDir: {}
        name: prometheus-storage-volume
status:
  conditions:
  - lastTransitionTime: 2018-09-20T02:13:03Z
    lastUpdateTime: 2018-09-20T02:13:03Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 4
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
