apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fah
  name: fah
  namespace: fah
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fah
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fah
    spec:
      containers:
      - image: rgardler/fah
        imagePullPolicy: Always
        name: fah
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: google/cadvisor
        imagePullPolicy: Always
        name: cadvisor
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-09-26T15:14:12Z
    lastUpdateTime: 2018-09-26T15:14:12Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3

